version: "3"
services:
  ms-sql-server:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "G73gle73!"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
  weatherapi:
    image: huamu/dockerhub:weatherapidemo
    restart: always
    ports:
      - "8080:80"
      - "8081:443"      
    depends_on:
      - ms-sql-server
