version: "3"
services:
  #ms-sql-server: #服务名
  #  image: microsoft/mssql-server-linux:2017-latest
  #  environment:
  #    ACCEPT_EULA: "Y"
  #    SA_PASSWORD: "G73gle73!"
  #    MSSQL_PID: Express
  #  ports:
  #    - "1401:1433"
  #postgres-server:
  #  image: postgres
  #  environment:
  #    POSTGRES_PASSWORD: postgres
  #  ports:
  #    - "5678:5432"
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: weather
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 123456
    ports:
      - "3310:3306"

  weather-api:
    build:
      context: weatherapi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      #- ms-sql-server
      - mysql-server
